Repository erda-project/erda-analyzer, pull requests merged in 2021-09, with the labels that each got.

#33 enhance version naming
  VERSION
  build.sh
  make-version.sh
Labels: enhancement

#36 Add analyzer-trace module
  VERSION
  analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/Constants.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/MetricConstants.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/constant/SpanConstants.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/functions/MetricEventCorrectFunction.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/models/MetricEvent.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/schemas/SpanEventSchema.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/utils/ConvertUtils.java
  analyzer-common/src/main/java/cloud/erda/analyzer/common/watermarks/BoundedOutOfOrdernessWatermarkGenerator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/AvgFunctionAggregator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/MaxFunctionAggregator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/MinFunctionAggregator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/PercentFunctionAggregator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/SumFunctionAggregator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/operators/EqualFunctionOperator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/operators/GreaterThanFunctionOperator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/operators/GreaterThanOrEqualFunctionOperator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/operators/LessThanFunctionOperator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/operators/LessThanOrEqualFunctionOperator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/operators/NotEqualFunctionOperator.java
  analyzer-tracing/pom.xml
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/Main.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/FixedEventTimeTrigger.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricFieldAggregateFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricMetaFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricTagGroupFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SlowOrErrorMetricFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanCorrectFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanMetricCompatibleFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanSchema.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanServiceGroupFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanServiceReduceFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanServiceTagCheckFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanTimestampAssigner.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanToServiceMetricFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/TransactionAnalysisFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/model/Relation.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/model/Span.java
  analyzer-tracing/src/main/resources/application.properties
  analyzer-tracing/src/main/resources/logback.xml
  dice.yml
  erda.yml
  pipeline.yml
  pom.xml
Labels: enhancement, approved

#43 Fix Exception while applying AggregateFunction in aggregating state
  analyzer-common/src/main/java/cloud/erda/analyzer/common/models/MetricEvent.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregator.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregatorDefine.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/FunctionAggregatorFactory.java
  analyzer-runtime/src/main/java/cloud/erda/analyzer/runtime/expression/functions/aggregators/MedianFunctionAggregator.java
  analyzer-tracing/pom.xml
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/Main.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/FieldAggregator.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricFieldAggregateFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricFieldProcessFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricMetaFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricTagGroupFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/StatsAccumulator.java
Labels: approved

#45 Use MetricFieldAggregateFunction
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/Main.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricFieldProcessFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/MetricTagGroupFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/SpanToServiceMetricFunction.java
  analyzer-tracing/src/main/java/cloud/erda/analyzer/tracing/functions/TransactionAnalysisFunction.java
Labels: approved
